
STATE_DISTRICT_MAPPING = {
    "Alor Gajah": "Melaka",
    "Bachok": "Kelantan",
    "Bagan Datuk": "Perak",
    "Bahagian Betong": "Sarawak",
    "Bahagian Bintulu": "Sarawak",
    "Bahagian Kapit": "Sarawak",
    "Bahagian Kuching": "Sarawak",
    "Bahagian Limbang": "Sarawak",
    "Bahagian Miri": "Sarawak",
    "Bahagian Mukah": "Sarawak",
    "Bahagian Samarahan": "Sarawak",
    "Bahagian Sarikei": "Sarawak",
    "Bahagian Serian": "Sarawak",
    "Bahagian Sibu": "Sarawak",
    "Bahagian Sri Aman": "Sarawak",
    "Baling": "Kedah",
    "Bandar Baru": "Kedah",
    "Barat Daya": "Pulau Pinang",
    "Batang Padang": "Perak",
    "Batu Pahat": "Johor",
    "Beaufort": "Sabah",
    "Bentong": "Pahang",
    "Bera": "Pahang",
    "Besut": "Terengganu",
    "Cameron Highland": "Pahang",
    "Dungun": "Terengganu",
    "Gombak": "Selangor",
    "Gua Musang": "Kelantan",
    "Hilir Perak": "Perak",
    "Hulu Langat": "Selangor",
    "Hulu Perak": "Perak",
    "Hulu Selangor": "Selangor",
    "Hulu Terengganu": "Terengganu",
    "Jasin": "Melaka",
    "Jelebu": "Negeri Sembilan",
    "Jeli": "Kelantan",
    "Jempol": "Negeri Sembilan",
    "Jerantut": "Pahang",
    "Johor Bahru": "Johor",
    "Kampar": "Perak",
    "Kemaman": "Terengganu",
    "Keningau": "Sabah",
    "Kerian": "Perak",
    "Kinta": "Perak",
    "Klang": "Selangor",
    "Kluang": "Johor",
    "Kota Bahru": "Kelantan",
    "Kota Belud": "Sabah",
    "Kota Kinabalu": "Sabah",
    "Kota Marudu": "Sabah",
    "Kota Setar": "Kedah",
    "Kota Tinggi": "Johor",
    "Kuala Kangsar": "Perak",
    "Kuala Krai": "Kelantan",
    "Kuala Langat": "Selangor",
    "Kuala Lumpur": "Kuala Lumpur",  # Federal Territory
    "Kuala Muda": "Kedah",
    "Kuala Nerus": "Terengganu",
    "Kuala Pilah": "Negeri Sembilan",
    "Kuala Selangor": "Selangor",
    "Kuala Terengganu": "Terengganu",
    "Kuantan": "Pahang",
    "Kubang Pasu": "Kedah",
    "Kudat": "Sabah",
    "Kulai": "Johor",
    "Kulim": "Kedah",
    "Labuan": "Labuan",  # Federal Territory
    "Lahad Datu": "Sabah",
    "Langkawi": "Kedah",
    "Larut Matang": "Perak",
    "Lipis": "Pahang",
    "Machang": "Kelantan",
    "Manjung": "Perak",
    "Maran": "Pahang",
    "Marang": "Terengganu",
    "Melaka Tengah": "Melaka",
    "Mersing": "Johor",
    "Muallim": "Perak",
    "Muar": "Johor",
    "Padang Terap": "Kedah",
    "Papar": "Sabah",
    "Pasir Mas": "Kelantan",
    "Pasir Puteh": "Kelantan",
    "Pekan": "Pahang",
    "Penampang": "Sabah",
    "Pendang": "Kedah",
    "Perak Tengah": "Perak",
    "Perlis": "Perlis",
    "Petaling": "Selangor",
    "Pitas": "Sabah",
    "Pokok Sena": "Kedah",
    "Pontian": "Johor",
    "Port Dickson": "Negeri Sembilan",
    "Raub": "Pahang",
    "Rembau": "Negeri Sembilan",
    "Rompin": "Pahang",
    "Sabak Bernam": "Selangor",
    "Sandakan": "Sabah",
    "Seberang Perai Selatan": "Pulau Pinang",
    "Seberang Perai Tengah": "Pulau Pinang",
    "Seberang Perai Utara": "Pulau Pinang",
    "Segamat": "Johor",
    "Selama": "Perak",
    "Sepang": "Selangor",
    "Seremban": "Negeri Sembilan",
    "Setiu": "Terengganu",
    "Sik": "Kedah",
    "Tampin": "Negeri Sembilan",
    "Tanah Merah": "Kelantan",
    "Tangkak": "Johor",
    "Tawau": "Sabah",
    "Temerloh": "Pahang",
    "Timur Laut": "Pulau Pinang",
    "Tuaran": "Sabah",
    "Tumpat": "Kelantan",
    "Yan": "Kedah",
    "Kunak": "Sabah",
    "Labuk Sugut": "Sabah",
    "Putatan": "Sabah",
    "Ranau": "Sabah",
    "Semporna": "Sabah",
    "Sipitang": "Sabah",
    "Tambunan": "Sabah",
    "Tenom": "Sabah",
    "Putrajaya": "Putrajaya",  # Federal Territory
    "Rompin": "Pahang" 
}